### ISSUE TITLE
reorganize repo and wiki per audience

### ISSUE THREAD

**Issue by RoseTHERESA** [WomenWhoCode/MobileStudyGroup#1]
The repo should be for wwc leaders | organizers.  
The wiki for attendees | students.

**Comment by LauraKirby** [comment]
Good thinking Rose. I have just sent you and Kaylyn an email about the next steps. Let's add content to what we have but not spend too much time restructuring.

**Comment by RoseTHERESA** [comment]
Issued superceded by website for students. Let's just hope it gets done...

**Comment by RoseTHERESA** [comment]
Organize content -- markdown files -- per audience,
with dedicated files for:
    organizers and leaders global
    organizers and leaders san francisco
    students -- beginners
    students -- intermediate
    students -- advanced
